### ISSUE TITLE
Should we do a (single) breaking update on develop?

### ISSUE THREAD

**Issue by chieltbest** [kvasir-io/mpl#11]
At this moment there are two main changes in proposal to the public interface of mpl that would be breaking: switching to ::value instead of implicit conversion, and switching the lambda argument around to the last position to be able to provide default lambdas.
The main question here is whether to do this in one breaking update, or to separate it into multiple changes which we would then have the option to deprecate implicit conversion instead of removing it outright.
Either way it is important that we make these breaking changes before a first version is put on master, as we could then permanently freeze the public interface, helping user adoption.

**Comment by odinthenerd** [comment]
I think switching to ::value should be a single breaking update now, anyone relying on it will break at some point, might as well break them now before more use it ;)

**Comment by CvRXX** [comment]
I would like one update with all the interface semantics breaks in it. So we could finish the port for bit in one go.

**Comment by chieltbest** [comment]
I will make a branch to make the breaking changes on that can be merged to development all at once, this seems like the best solution to me.
