### ISSUE TITLE
"private" namespaces in TMP anre named "detail" not "impl"

### ISSUE THREAD

**Issue by odinthenerd** [kvasir-io/mpl#2]
whether we like it or not we should probably adhere to the convention of hiding stuff that the user should not see in a "detail" namespace rather than "impl" as we do now. For example tooling my know to omit "detail" where it would not know to omit "impl".

this is not super pressing though, we should probably just make the change as we migrate to continuation implementations.

**Comment by chieltbest** [comment]
I originally named the namespace impl because it had to be accessible for user defined implementations for various list types.
Since we are switching to the continuation based implementation I am going to close this issue as it is no longer relevant.
