### ISSUE TITLE
f should only be used to denote a nested alias and not a nested type

### ISSUE THREAD

**Issue by odinthenerd** [kvasir-io/mpl#3]
we should stick to the convention that a nested type is named type. 

this is not super important since its is essentially only in our internal implementation and can be phased out while migrating to continuations.

**Comment by chieltbest** [comment]
By design the library should not have any types that you must get an alias of to get the result, which means there are no user facing "type"-like aliases.
As this is the case I would say the usage of the "f" aliases in the library internals is justified.

**Comment by odinthenerd** [comment]
yes I agree its not a public interface thing, but It does seem unclean

**Comment by odinthenerd** [comment]
I think we have replaced everything at this point
