### ISSUE TITLE
Add CMake installs

### ISSUE THREAD

**Issue by Quincunx271** [kvasir-io/mpl#46]
[Relevant article on how to do CMake "right"](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/).

Currently, the library has to be used by `add_subdirectory()` or by adding `src` to the include path. Adding the `install` commands will make this library conform to CMake best practices if I understand that article correctly. It would allow one to write `find_package(kvasir_mpl REQUIRED)` and just use `target_link_libraries`

Although I'm unsure what the target for kvasir_mpl should be:

```
target_link_libraries(my_target Kvasir::mpl) # Formatted like in the Readme
target_link_libraries(my_target kvasir_mpl::kvasir_mpl)
```

As far as I know, the exported target does have to have a namespace, but I'm not the most knowledgeable person when it comes to CMake.

**Comment by chieltbest** [comment]
Pull request was merged, closing.
